# Generated by Django 5.1.6 on 2026-03-05

import django.db.models.deletion
from django.db import migrations, models


def assign_provider_to_existing_invoices(apps, schema_editor):
    Provider = apps.get_model("billing", "Provider")
    Invoice = apps.get_model("billing", "Invoice")
    InvoiceLine = apps.get_model("billing", "InvoiceLine")

    fallback_provider = Provider.objects.order_by("id").first()
    if fallback_provider is None:
        fallback_provider = Provider.objects.create(
            name="Unknown Provider",
            address="Unknown",
            tax_id="UNKNOWN",
        )

    for invoice in Invoice.objects.all():
        line = (
            InvoiceLine.objects.filter(invoice_id=invoice.id)
            .select_related("barrel__provider")
            .first()
        )
        invoice.provider_id = line.barrel.provider_id if line is not None else fallback_provider.id
        invoice.save(update_fields=["provider"])


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="provider",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="billing.provider",
            ),
        ),
        migrations.RunPython(assign_provider_to_existing_invoices, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="invoice",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="billing.provider",
            ),
        ),
    ]
